CREATE TABLE task (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    execution_interval_days integer NOT NULL,
    check_from timestamp(6) with time zone,
    last_time_executed timestamp(6) with time zone,
    name varchar(255),
    platform varchar(255) CHECK (platform IN ('SPOTIFY','YOUTUBE')),
    playlist_id varchar(255),
    user_id varchar(255)
);

CREATE TABLE task_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint REFERENCES task,
    external_reference_id varchar(255),
    item_type varchar(255) CHECK (item_type IN ('ARTIST','PLAYLIST'))
);

CREATE TABLE added_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint REFERENCES task,
    added_at timestamp(6) with time zone,
    external_id varchar(255),
    title varchar(255)
);

CREATE TABLE spotify_token (
    user_id varchar(255) PRIMARY KEY,
    expires_at timestamp(6) with time zone,
    access_token varchar(2048),
    refresh_token varchar(2048)
);